spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://stanlin.wanari.com:5432/spring-multidb-view
        username: spring-multidb-view
        password: spring-multidb-view

liquibase:
    change-log: classpath:/liquibase/master.xml